const menu = [
  {
    id: 1,
    title: "Chicken Biryani",
    category: "biryani",
    price: 369,
    img: "./images/biryani-1.jpg",
    desc: `Chicken Dum Biryani (2-3Pcs) + Butter Chicken Masala (4Pcs) + Malabar Paratha(1No)+ Small Angoori Gulab Jamun (4Pcs) + Raita + Salad- Mouth-watering combination of two of India’s classic favorite dishes. `,
  },
  {
    id: 2,
    title: "Margherita Pizza",
    category: "pizza",
    price: 238,
    img: "./images/pizza-1.jpg",
    desc: `A classic 100% Dairy Cheese pizza that simplifies your life, well in choosing the right pizza at least. Fresh in-house tomato spread flirts with just the right mix of mozzarella n cheddar cheese. So stringy, you can not pull away. Literally`,
  },
  {
    id: 3,
    title: "Bun Tikki Burger",
    category: "burger",
    price: 98,
    img: "./images/burger-1.jpg",
    desc: `Save Rs. with this combo of Bun Tikki Burger+ Bun Tikki Burger. Add Fries(M) and Beverage to Save Rs.53`,
  },
  {
    id: 4,
    title: "Veg Biryani",
    category: "biryani",
    price: 249,
    img: "./images/biryani-2.jpg",
    desc: `For all the Barbeque lovers, an assortment of fresh vegetables barbecued with a smoky finesse and cooked with aromatic Basmati rice in the Dum style" Kcal - 1141`,
  },
  {
    id: 5,
    title: "Vegetable Noodles",
    category: "noodles",
    price: 249,
    img: "./images/noodles-1.jpg",
    desc: `Delicate, fresh, hand made noodles, prepared in house daily, these are extra thin and a rare treat. Eaten once, they are addictive.`,
  },
  {
    id: 6,
    title: "Paneer Tikka Biryani",
    category: "biryani",
    price: 299,
    img: "./images/biryani-3.jpg",
    desc: `Cottage Cheese marinated in Indian spices and hung curd cooked in clay oven -Tandoor layered with aromatic rice. Served with Raita. Kcal - 803`,
  },
  {
    id: 7,
    title: "Cheese Onion Pizza",
    category: "pizza",
    price: 299,
    img: "./images/pizza-2.jpg",
    desc: `Delightfully fresh in-house tomato spread mingles with 100% dairy cheese with just the right mix of mozzarella n cheddar cheese, layered judiciously with freshly cut capsicums n onions to add their zing.`,
  },
  {
    id: 8,
    title: "Cheesy Chicken Pizza",
    category: "pizza",
    price: 349,
    img: "./images/pizza-3.jpg",
    desc: `Add some spice in life with chunks of tangy and spicy chilly chicken marinated in your favorite ChinJabi style. Made with delightfully fresh in-house tomato spread while our highly secretive mix of 100% Real Dairy Cheese just melts in the mouth. Totally delightful`,
  },
  {
    id: 9,
    title: "Crispy Chicken Burger",
    category: "burger",
    price: 129,
    img: "./images/burger-3.jpg",
    desc: `Freshly fried spiced chicken patty topped with freshly julliened cabbage & onion coleslaw between classic toasted buns. Crisp up your life, satisfy your craving and never look back.`,
  },
  {
    id: 10,
    title: "Vegetable Singapore Noodles",
    category: "noodles",
    price: 385,
    img: "./images/noodles-3.jpg",
    desc: `Delicate, fresh, hand made noodles, prepared in house daily, these are extra thin and a rare treat. Eaten once, they are addictive.Thin rice noodles.`,
  },
  {
    id: 11,
    title: "BBQ Chicken Burger",
    category: "burger",
    price: 189,
    img: "./images/burger-2.jpg",
    desc: `Save up to 20% with this delicious combo of 1 BBQ Chicken Burger + 1 Crispy Chicken Wrap`,
  },
  {
    id: 12,
    title: "Chicken Garlic Noodles",
    category: "noodles",
    price: 345,
    img: "./images/noodles-2.jpg",
    desc: `Delicate, fresh, hand made noodles, prepared in house daily, these are extra thin and a rare treat. Eaten once, they are addictive.`,
  },
];
export default menu;
